version: '3.8'

services:
  app:
    container_name: tselbe-app
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - tselbe-network

  redis:
    image: redis:latest
    container_name: tselbe-redis
    command: redis-server --requirepass redispasswordtsel1122334455xyz
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - tselbe-network

  db:
    container_name: tsel-db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - tselbe-network

volumes:
  postgres_data:
  redis-data:

networks:
  tselbe-network:
    driver: bridge
