version: '3.8'

services:
  db:
    container_name: tsel-db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    restart: unless-stopped
volumes:
  postgres_data:
